config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
  get 'users/sign_out' => 'devise/sessions#destroy'
  end


  root 'home#index'
  resources :promotions do
    post 'generate_coupons', on: :member
  end

  resources :product_categories
  resources :coupons, only: %i[index] do
    post 'inactivate', on: :member
    post 'activate', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :coupons, param: :code, only: %i[show] do
        post 'burn', on: :member
      end
    end 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :promotion

  enum status: { active: 0, inactive: 20, burn: 10 }
  validates :order, presence: true, on: :coupon_burn

  def self.search(search)
    if search
      where(code: search)
    else
      all
    end
  end

  def title
    "#{code} (#{Coupon.human_attribute_name("status.#{status}")})"
  end

  def as_json(options = {})
    super({ methods: %i[discount_rate expiration_date],
            only: %i[] }.merge(options))
  end

  def burn!(order)
    self.order = order
    self.status = :burn
    save!(context: :coupon_burn)
  end

  private

  def discount_rate
    promotion.discount_rate
  end

  def expiration_date
    I18n.l(promotion.expiration_date)
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :product_category_promotions, dependent: :destroy
  validates :name, :code, presence: true
  validates :code, uniqueness: true
end

app/models/product_category_promotion.rb
class ProductCategoryPromotion < ApplicationRecord
  belongs_to :product_category
  belongs_to :promotion
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_many :coupons, dependent: :destroy
  has_many :product_category_promotions
  has_many :product_categories, through: :product_category_promotions

  validates :name, :code, :discount_rate,
            :coupon_quantity, :expiration_date,
            presence: true
  validates :name, :code, uniqueness: true

  def generate_coupons!
    raise 'Cupons já foram gerados' if coupons.any?

    coupons
      .create_with(created_at: Time.zone.now, updated_at: Time.zone.now)
      .insert_all!(generate_coupons_code)
  end
end

  private

def generate_coupons_code
  ((coupons.count + 1)..coupon_quantity).map do |number|
    { code: "#{code}-#{'%04d' % number}" }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validate :email_domain

  def email_domain
    return if email.include?('@locaweb.com.br')

    errors.add(:email, :domain_invalid)
  end
end

app/controllers/api/v1/api_controller.rb
module Api
  module V1
    class ApiController < ActionController::API
    end
  end
end

app/controllers/api/v1/coupons_controller.rb
module Api
  module V1
    class CouponsController < ApiController
      before_action :verify_order_code, only: %i[burn]

      def show
        @coupon = Coupon.find_by!(code: params[:code])
        render json: @coupon, status: :ok
      rescue ActiveRecord::RecordNotFound
        render json: 'Cupom não encontrado', status: :not_found
      end

      def burn
        @coupon = Coupon.find_by!(code: params[:code])
        @coupon.burn!(params[:order][:code])
        render json: 'Cupom utilizado com sucesso', status: :ok
      rescue ActiveRecord::RecordInvalid
        render json: '', status: :unprocessable_entity
      end

      private

      def verify_order_code
        return if params.dig(:order, :code)

        render json: '', status: :precondition_failed
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: %i[inactivate activate]

  def inactivate
    @coupon.inactive!
    flash[:success] = t('.success')
    redirect_to @coupon.promotion
  end

  def activate
    @coupon.active!
    flash[:notice] = t('.notice')
    redirect_to @coupon.promotion
  end

  def index
    @coupons = Coupon.search(params[:query])
  end

  private

  def set_coupon
    @coupon = Coupon.find(params[:id])
  end

  def search_params
    params.require(:coupon).permit(:code, :status, :query)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product_category, only: %i[show edit update destroy]

  def index
    @product_categories = ProductCategory.all
  end

  def new
    @product_category = ProductCategory.new
  end

  def edit; end

  def show; end

  def create
    @product_category = ProductCategory.new(product_category_params)
    if @product_category.save
      redirect_to @product_category
    else
      render :new
    end
  end

  def update
    if @product_category.update(product_category_params)
      redirect_to product_category_path(@product_category)
    else
      render :edit
    end
  end

  def destroy
    @product_category.destroy
    redirect_to product_categories_path
  end

  private

  def product_category_params
    params
      .require(:product_category)
      .permit(:name, :code)
  end

  def set_product_category
    @product_category = ProductCategory.find(params[:id])
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_promotion, only: %i[show edit destroy update generate_coupons]

  def index
    @promotions = Promotion.all
  end

  def edit; end

  def show; end

  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = Promotion.new(promotion_params)
    if @promotion.save
      redirect_to @promotion
    else
      render :new
    end
  end

  def update
    if @promotion.update(promotion_params)
      redirect_to @promotion
    else
      render :edit
    end
  end

  def destroy
    @promotion.destroy
    redirect_to promotions_path
  end

  def generate_coupons
    @promotion.generate_coupons!
    flash[:success] = 'Cupons gerados com sucesso'
    redirect_to @promotion
  end

  private

  def set_promotion
    @promotion = Promotion.find(params[:id])
  end

  def promotion_params
    params
      .require(:promotion)
      .permit(:name, :description, :code,
              :discount_rate, :expiration_date, :coupon_quantity,
              product_category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coupons/_coupon.html.erb
   <dl>
      <dt><%= Coupon.human_attribute_name(:code) %></dt>
      <dd><%= coupon.title %></dd>
    </dl>
  <% if coupon.active? %>
    <%= link_to t('.inactivate'), inactivate_coupon_path(coupon), method: :post %> 
    <% else %>
    <%= link_to t('.active'), activate_coupon_path(coupon), method: :post %>
    <% end  %>

app/views/coupons/index.html.erb
<% @coupons.each do |coupon| %>
    <%= render partial: 'coupon', locals: { coupon: coupon } %>
    <%= render partial: 'promotions/promotion_fields', locals: { promotion: coupon.promotion } %>
<% end %>
    <% if @coupons.empty? %>
    <p>Nenhum cupom encontrado</p>
<% end %>

app/views/home/index.html.erb
<h1>Sistema de Promoções</h1>
<p>Boas vindas ao sistema de gestão de promoções</p>

<div class="container">
  <nav>
    <% if user_signed_in? %>
    <%= form_tag coupons_path, :method => 'get' do %>
    <%= text_field_tag :query, params[:query], class: "ls-field" %>
    <%= submit_tag 'Buscar cupom', :name => nil, class: "ls-btn" %>
    <% end %>
      <%= link_to 'Categorias de produto', product_categories_path %></p>  
      <%= link_to 'Promoções', promotions_path %>
<% end %>
 </nav>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema de Promoção</title>
   <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container-fluid p-3">

      <% if notice %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <%end%>
      <% if alert %>
        <div class="alert alert-warning" role="alert"><%= alert %></div>
      <%end%>
      <% if flash[:success] %>
        <div class="alert alert-success" role="alert"><%= success %></div>
      <% end %>
      
      <% if user_signed_in? %>
        <p><%= current_user.email %>
        <%= link_to 'Logout', destroy_user_session_path, :method => :delete %></p> 
        <% else %>
        <p><%= link_to 'Login', new_user_session_path %></p>
        <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/product_categories/_form.html.erb
  <% product_category.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
  <%= form_with model: product_category, local: true do |f| %>
  <div class="form-product-categories" >
    <div class="form-inline">
      <%= f.label :name %>
      <%= f.text_field :name,class: "form-control w-20 mb-2 mr-sm-2 mb-sm-0" %>
      <%= f.label :code %>
      <%= f.text_field :code, class: "form-control w-30 mb-2 mr-sm-2 mb-sm-0" %>
        <%= f.submit 'Salvar', class: "btn btn-primary" %>

    </div>
  </div >
  <br>
  <% end %>

  

app/views/product_categories/edit.html.erb
  <h1>  Editar categoria de produto</h1>
    <%= link_to 'Voltar', @product_category %>

  <%= render partial: "form", locals: {product_category: @product_category} %>

app/views/product_categories/index.html.erb
<% @product_categories.each do |product_category| %>
  <h3><%= link_to  product_category.name, product_category %></h3>
  <p><strong><%= product_category.code %></strong> </p>
<% end %>

<% if @product_categories.empty? %>
  <div class="alert alert-info mt-3" role="alert">Nenhuma categoria cadastrada</div>
<% end  %>
<%=  link_to 'Criar uma nova categoria', new_product_category_path  %>
<%=  link_to 'Voltar', root_path %>

app/views/product_categories/new.html.erb
<h3>Adicionar nova categoria de produto<h3>
<%= render partial: "form", locals: {product_category: @product_category} %>

app/views/product_categories/show.html.erb
<%= link_to 'Voltar', product_categories_path %>

  <%= @product_category.name %>
  <%= @product_category.code %>
  
<%= link_to 'Editar', edit_product_category_path %>
<%= link_to 'Apagar', product_category_path(@product_category), method: :delete %>

app/views/promotions/_form.html.erb
  <% promotion.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>

<%= form_with model: promotion, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control w-50 mb-2 mr-sm-2 mb-sm-0" %><br>
  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control w-50 mb-2 mr-sm-2 mb-sm-0" %><br>
  <%= f.label :code %>
  <%= f.text_field :code, class: "form-control w-50 mb-2 mr-sm-2 mb-sm-0" %><br>
  <%= f.label :discount_rate %>
  <%= f.number_field :discount_rate, class: "form-control w-50 mb-2 mr-sm-2 mb-sm-0" %><br>
  <%= f.label :coupon_quantity %>
  <%= f.number_field :coupon_quantity, min: 0,class: "form-control w-50 mb-2 mr-sm-2 mb-sm-0" %><br>
  <%= f.label :expiration_date %>
  <%= f.date_field :expiration_date %><br>
  <%= f.label :product_category_ids %>
  <%= f.collection_check_boxes :product_category_ids, ProductCategory.all, :id, :name %>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/promotions/_promotion_fields.html.erb
<%= promotion.name %>

    <dl>
      <dt>Nome</dt>
      <dd><%= promotion.name %>
      <dt>Descrição</dt>
      <dd><%= promotion.description %></dd>   
      <dt>Desconto em porcentagem</dt>
      <dd><%= number_to_percentage promotion.discount_rate, precision: 2, separator:',' %></dd> 
      <dt>Cupom</dt>
      <dd><%= promotion.code %></dd>
      <dt>Data de término:</dt>
      <dd><%= promotion.expiration_date.strftime('%d/%m/%Y') %></dd>
      <dt>Número de cupons:</dt>
      <dd><%= promotion.coupon_quantity %></dd>
    </dl>

    <% promotion.product_categories.each do |product_category| %>
     <p><%= product_category.name %></p>
    <% end %>

app/views/promotions/edit.html.erb
  <h3>Editar promoção</h3>
  <%= render partial: "form", locals: { promotion: @promotion } %>

  <%=  link_to 'Voltar', root_path %>

app/views/promotions/index.html.erb
<div class="container">
<table>
<table class="table table-bordered">

  <tbody>
      <tr>
      <th>Nome:</th>
      <th>Descrição:</th>
      <th>Desconto:</th>
    </tr>
    <% @promotions.each do |promotion| %>
      <tr>
        <td><%= link_to promotion.name, promotion %></td> 
        <td><%= promotion.description %></td>
        <td><%= number_to_percentage  promotion.discount_rate, precision: 2 %></td>
      </tr>
<% end %>
  </tbody>
</table>
  <thead>

  </thead>
</table>

<% if @promotions.empty? %>
  <div class="alert alert-info mt-3" role="alert">Nenhuma promoção cadastrada</div>
<% end %>
<%= link_to 'Registrar uma promoção', new_promotion_path %>
<%= link_to 'Voltar', root_path %> 
</div>

app/views/promotions/new.html.erb
<h3>Adicionar promoção</h3>
    <%= render partial: "form", locals: { promotion: @promotion } %>

    <%=  link_to 'Voltar', root_path %> 

app/views/promotions/show.html.erb
  <%= link_to 'Voltar', promotions_path %>
  <%= link_to 'Editar', edit_promotion_path(@promotion) %>
  <%= link_to 'Apagar', promotion_path(@promotion), method: :delete %> 



      <%= render partial: 'promotion_fields', locals: { promotion: @promotion } %>
        
      <% if @promotion.coupon_quantity > @promotion.coupons.count %>
      <%= link_to 'Emitir cupons', generate_coupons_promotion_path(@promotion), method: :post %>
   <% end %>
    <h1>Cupons</h1>
    <%= render @promotion.coupons %>

  